title: Saad Amin's Website
description: >- # this means to ignore newlines until "baseurl:"
  Saad Amin's website
baseurl:
twitter_username: saada2006
github_username:  saada2006

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "neon"
plugins:
  - jekyll-feed
  - jekyll-include-cache

author:
  name: "Saad Amin"
  bio: "Research intern at UCSF. MSJHS '24. saada#4211" 

include:
  - _pages

permalink: /:categories/:title/
paginate_path: /page:num/

permalink: none