title: Saad's blog
description: >- # this means to ignore newlines until "baseurl:"
  Home
baseurl:

minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed
  - jekyll-include-cache

author:
  name: "Saad Amin"
  bio: "GPU Compute Programmer" 

include:
  - _pages

permalink: /:categories/:title/
paginate_path: /page:num/

permalink: none

masthead_title: "Home"

collections:
  posts:
    output: true
    permalink: /:collection/:path/